name: Run Daily ETF Script

on:
  schedule:
    - cron: '0 13 * * *'  # 13:00 UTC ≈ 9am in Toronto during EDT, 8am during EST
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run daily snapshot
        run: python daily_etf_yield_tracker.py

      - name: Commit and push CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add current_etf_yields_canada.csv current_etf_yields_us.csv || true
          git commit -m "Auto-update daily ETF yields" || echo "No changes to commit"
          git push
