name: Run Historical Yield Tracker

on:
  schedule:
    - cron: '0 6 * * 1'  # Mondays 06:00 UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run-historical:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run historical tracker
        run: python historical_yield_tracker.py

      - name: Commit and push historical CSVs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add historical_etf_yields_canada.csv historical_etf_yields_us.csv || true
          git commit -m "Update historical yield data (weekly run)" || echo "Nothing to commit"
          git push
