# Purpose: On-demand graph generator for a single ticker.
# Behavior:
#   - Takes user-supplied 'ticker' via workflow_dispatch input
#   - Runs plot_ticker_graph.py to produce graphs/<TICKER>_history.png
#   - Commits the PNG to the repository
# Schedule: none (manual only). Trigger via Actions → "Run workflow".

name: Plot Ticker Graph (On Demand)

on:
  workflow_dispatch:
    inputs:
      ticker:
        description: "Ticker symbol (Yahoo format, e.g., EIT-UN.TO)"
        required: true
        type: string

permissions:
  contents: write

jobs:
  plot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas yfinance matplotlib

      - name: Generate graph
        run: |
          python plot_ticker_graph.py "${{ github.event.inputs.ticker }}"

      - name: Commit and push PNG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add graphs/*.png || true
          git commit -m "Add graph for ${{ github.event.inputs.ticker }}" || echo "Nothing to commit"
          git push
