name: Plot Single Ticker

on:
  workflow_dispatch:
    inputs:
      ticker:
        description: "Ticker symbol (e.g., ULTY or EIT-UN.TO)"
        required: true
        type: string
      currency:
        description: "Which historical CSV to use"
        required: true
        type: choice
        options: [USD, CAD]
        default: USD
      outdir:
        description: "Output directory for PNG files"
        required: true
        type: string
        default: graphs
      force_replot:
        description: "Force re-plot even if PNG is already up-to-date?"
        required: true
        type: choice
        options: [no, yes]
        default: no

permissions:
  contents: write

jobs:
  plot-single:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (plotting + bootstrap scraping)
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then
            pip install -r requirements.txt
          else
            # Core libs for your plotter and for history_updater bootstrap path
            pip install pandas numpy matplotlib yfinance requests beautifulsoup4 lxml
          fi

      - name: Generate graph
        env:
          FORCE: ${{ github.event.inputs.force_replot }}
        run: |
          mkdir -p "${{ github.event.inputs.outdir }}"
          if [ "$FORCE" = "yes" ]; then
            FORCE_FLAG="--force"
          else
            FORCE_FLAG=""
          fi
          python plot_ticker_graph.py "${{ github.event.inputs.ticker }}" \
            --currency "${{ github.event.inputs.currency }}" \
            --outdir "${{ github.event.inputs.outdir }}" $FORCE_FLAG

      - name: List outputs
        run: |
          echo "=== Output directory ==="
          ls -la "${{ github.event.inputs.outdir }}" || true

      - name: Commit and push artifacts (PNG + updated ticker lists)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f "${{ github.event.inputs.outdir }}"/*.png || true
          git add -f us_tickers.txt ca_tickers.txt || true
          git commit -m "Graph for ${{ github.event.inputs.ticker }} (${{ github.event.inputs.currency }})" || echo "Nothing to commit"
          git push || true
