name: Plot Ticker Graph (On Demand)

on:
  workflow_dispatch:
    inputs:
      ticker:
        description: "Ticker (Yahoo format, e.g., ULTY or EIT-UN.TO)"
        required: true
        type: string
      currency:
        description: "Currency"
        required: true
        type: choice
        options: [CAD, USD]
        default: USD

permissions:
  contents: write

jobs:
  plot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show Python & files
        run: |
          python --version
          ls -la
          ls -la graphs || true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib

      - name: Generate graph
        env:
          INPUT_TICKER: ${{ github.event.inputs.ticker }}
          INPUT_CURRENCY: ${{ github.event.inputs.currency }}
        run: |
          mkdir -p graphs
          python plot_ticker_graph.py "${INPUT_TICKER}" "${INPUT_CURRENCY}"

      - name: List outputs
        run: |
          ls -la graphs || true
          tail -n +1 graphs/*_debug_sample.csv || true

      - name: Commit and push artifacts
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f graphs/*.png graphs/*_debug_sample.csv || true
          git commit -m "Add graph for ${{ github.event.inputs.ticker }} (${{ github.event.inputs.currency }})" || echo "Nothing to commit"
          git push || true
