name: Plot Tickers From File

on:
  workflow_dispatch:
    inputs:
      tickers_file:
        description: "Choose ticker file from repository"
        required: true
        type: choice
        options:
          - us_tickers.txt
          - ca_tickers.txt
        default: us_tickers.txt
      outdir:
        description: "Output directory for PNG files"
        required: true
        type: string
        default: graphs

permissions:
  contents: write

jobs:
  plot-from-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas numpy matplotlib

      - name: Decide currency based on file
        id: decide
        run: |
          case "${{ github.event.inputs.tickers_file }}" in
            us_tickers.txt) echo "currency=USD" >> $GITHUB_OUTPUT ;;
            ca_tickers.txt) echo "currency=CAD" >> $GITHUB_OUTPUT ;;
            *) echo "currency=USD" >> $GITHUB_OUTPUT ;; # fallback
          esac

      - name: Generate graphs for all tickers
        shell: bash
        env:
          TICKERS_FILE: ${{ github.event.inputs.tickers_file }}
          CURRENCY: ${{ steps.decide.outputs.currency }}
          OUTDIR: ${{ github.event.inputs.outdir }}
        run: |
          set -euo pipefail
          if [ ! -f "$TICKERS_FILE" ]; then
            echo "ERROR: Tickers file not found: $TICKERS_FILE"
            exit 1
          fi

          mkdir -p "$OUTDIR"

          total=0; ok=0; failed=0
          while IFS= read -r line || [ -n "$line" ]; do
            ticker="$(echo "$line" | sed 's/^[[:space:]]*//;s/[[:space:]]*$//')"
            if [ -z "$ticker" ] || [[ "$ticker" =~ ^# ]]; then
              continue
            fi
            total=$((total+1))
            echo "::group::Plotting $ticker ($CURRENCY)"
            set +e
            python plot_ticker_graph.py "$ticker" --currency "$CURRENCY" --outdir "$OUTDIR"
            rc=$?
            set -e
            if [ $rc -eq 0 ]; then
              echo "[ok] $ticker"; ok=$((ok+1))
            else
              echo "[warn] Failed for $ticker (exit $rc)"; failed=$((failed+1))
            fi
            echo "::endgroup::"
          done < "$TICKERS_FILE"

          echo "Summary: total=$total ok=$ok failed=$failed"
          if [ $ok -eq 0 ]; then
            echo "No graphs produced."
          fi

      - name: Commit and push PNGs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f "${{ github.event.inputs.outdir }}"/*.png || true
          git commit -m "Add graphs from ${{ github.event.inputs.tickers_file }} (currency ${{ steps.decide.outputs.currency }})" || echo "Nothing to commit"
          git push || true
