# Purpose: On-demand graph generator for a single ticker.
# Adds a CAD/USD radio button and passes it to the script.

name: Plot Ticker Graph (On Demand)

on:
  workflow_dispatch:
    inputs:
      ticker:
        description: "Ticker symbol (Yahoo format, e.g., EIT-UN.TO)"
        required: true
        type: string
      currency:
        description: "Currency for history CSV"
        required: true
        type: choice
        options:
          - CAD
          - USD
        default: USD

permissions:
  contents: write

jobs:
  plot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
