# .github/workflows/plot_graph.yml
# Purpose: On-demand graph generator for a single ticker.
# Adds a currency selector (USD or CAD) and passes it correctly to the script.

name: Plot Ticker Graph (On Demand)

on:
  workflow_dispatch:
    inputs:
      ticker:
        description: "Ticker symbol (Yahoo format, e.g., ULTY or EIT-UN.TO)"
        required: true
        type: string
      currency:
        description: "Which historical CSV to use"
        required: true
        type: choice
        options: [USD, CAD]
        default: USD

permissions:
  contents: write

jobs:
  plot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib numpy

      - name: Generate graph
        run: |
          mkdir -p graphs
          python plot_ticker_graph.py "${{ github.event.inputs.ticker }}" --currency "${{ github.event.inputs.currency }}"

      - name: Commit and push PNG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f graphs/*.png || true
          git commit -m "Add graph for ${{ github.event.inputs.ticker }} (${{ github.event.inputs.currency }})" || echo "Nothing to commit"
          git push
